# Generated by Django 5.1.4 on 2024-12-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost_from', models.IntegerField()),
                ('cost_to', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
            ],
        ),
    ]
