# Generated by Django 5.1.4 on 2024-12-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_socialmediapost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="image_url",
            field=models.TextField(),
        ),
    ]
