# Generated by Django 5.1.4 on 2024-12-29 21:58

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    # Get the Tour model dynamically for migration purposes
    Tour = apps.get_model('server', 'Tour')

    for tour in Tour.objects.all():
        if not tour.slug:  # Only populate if slug is empty
            # Fallback for missing `title_en`
            base_slug = slugify(tour.title_en) if tour.title_en else f"tour-{tour.id}"
            unique_slug = base_slug
            counter = 1

            # Ensure uniqueness
            while Tour.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1

            tour.slug = unique_slug
            tour.save()


class Migration(migrations.Migration):
    dependencies = [
        ('server', '0006_rename_description_ukr_notification_description_ua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.RunPython(populate_slugs),
    ]
