# Generated by Django 5.1.4 on 2024-12-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_alter_tour_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourcategory',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='tourtype',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
