# Generated by Django 5.2.10 on 2026-01-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0009_tourcategory_ordering_tourtype_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmediapost",
            options={
                "ordering": ["display_order", "-id"],
                "verbose_name": "Пост Социальной Сети",
                "verbose_name_plural": "Посты Социальной Сети",
            },
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="description",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="socialmediapost",
            name="post_date",
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="display_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower number = shown first"
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Show this post on the website"
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="oembed_html",
            field=models.TextField(
                blank=True, help_text="Cached oEmbed HTML", null=True
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="thumbnail_url",
            field=models.URLField(
                blank=True, help_text="Thumbnail URL for preview", null=True
            ),
        ),
        migrations.AddField(
            model_name="socialmediapost",
            name="title",
            field=models.CharField(
                blank=True, help_text="Post title/caption", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="url",
            field=models.URLField(
                help_text="Post URL (Instagram or TikTok)", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="tour",
            name="cost_from",
            field=models.IntegerField(verbose_name="Стоимость от"),
        ),
        migrations.AlterField(
            model_name="tour",
            name="cost_to",
            field=models.IntegerField(verbose_name="Стоимость до"),
        ),
    ]
