# Generated by Django 5.2.10 on 2026-01-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0010_alter_socialmediapost_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediapost",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="Thumbnail URL for preview",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="socialmediapost",
            name="url",
            field=models.URLField(
                help_text="Post URL (Instagram or TikTok)", max_length=500, unique=True
            ),
        ),
    ]
