name: CodeGPT PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment for Django
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Django dependencies
      working-directory: backend
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # Step 3: Set up Node.js environment for Next.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Next.js dependencies
      working-directory: frontend
      run: npm install

    # Step 4: Install CodeGPT CLI (or other CodeGPT tools)
    - name: Install CodeGPT
      run: npm install -g codegpt@latest

    # Step 5: Analyze Django and Next.js code with CodeGPT
    - name: Analyze PR with CodeGPT
      working-directory: backend
      env:
        CODEGPT_API_KEY: ${{ secrets.CODEGPT_API_KEY }}
      run: |
        # Review Python (Django) files
        codegpt review-pr \
          --language python \
          --files "**/*.py" \
          --pr-number ${{ github.event.pull_request.number }} \
          --repo ${{ github.repository }}

    - name: Analyze Next.js code with CodeGPT
      working-directory: frontend
      env:
        CODEGPT_API_KEY: ${{ secrets.CODEGPT_API_KEY }}
      run: |
        # Review JavaScript/TypeScript (Next.js) files
        codegpt review-pr \
          --language javascript \
          --files "**/*.{js,jsx,ts,tsx}" \
          --pr-number ${{ github.event.pull_request.number }} \
          --repo ${{ github.repository }}

    # Step 6: Post Review Comments
    - name: Post Review Comments
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const reviewComments = fs.readFileSync('codegpt-comments.json', 'utf-8');
          const comments = JSON.parse(reviewComments);

          for (const comment of comments) {
            github.rest.pulls.createReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: comment.body,
              path: comment.path,
              position: comment.position,
            });
          }
