name: Review Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all branches and history

    - name: Fetch main branch
      run: git fetch origin preview

    - name: Generate Diff
      run: git diff origin/preview...HEAD > changes.diff

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: pip install openai

    - name: Run OpenAI Review
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: python analyze_code.py > analyze_code_feedback.txt

    - name: Post Review as Comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ### AI-Generated Code Review
          $(cat analyze_code_feedback.txt)
