name: CodeGPT PR Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai_pr_review:
    name: AI PR Review with CodeGPT
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment for Django
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Django Dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 3: Set up Node.js environment for Next.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Next.js Dependencies
        working-directory: frontend
        run: |
          npm install

      # Step 4: Install CodeGPT
      - name: Install CodeGPT
        run: npm install -g codegpt@latest

      # Step 5: Run CodeGPT Review for Suggestions
      - name: Run CodeGPT Review
        run: |
          npx codegpt pr-review analyze --token ${{ secrets.OPENAI_API_KEY }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Step 6: Explanation of the PR
      - name: Run CodeGPT Explanation
        run: |
          npx codegpt pr-review analyze --context "Explain the changes in this PR in detail." --token ${{ secrets.OPENAI_API_KEY }}
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Step 7: Run Tests for Django
      - name: Run Tests for Django
        working-directory: backend
        run: python manage.py test
